import { afterEach, beforeEach, expect, it, vi } from 'vitest';
import { browser } from '#imports';
import type { Browser } from 'wxt/browser';
import { startContentRuntime } from '@lib/content/runtime';
import type { BgToCs, CsToBg } from '@lib/messaging/protocol';

let messages: CsToBg[];
let receive: (message: BgToCs) => Promise<void>;
let dispose: (() => void) | undefined;
let disconnect: ReturnType<typeof vi.fn>;
beforeEach(() => {
  vi.useFakeTimers(); messages=[]; document.body.innerHTML='<label>Name<input name="name" /></label>';
  disconnect=vi.fn();
  const port={postMessage:(message:CsToBg)=>messages.push(message),disconnect,
    onMessage:{addListener:(listener:typeof receive)=>{receive=listener;}},onDisconnect:{addListener:vi.fn()}};
  vi.spyOn(browser.runtime,'connect').mockReturnValue(port as unknown as Browser.runtime.Port);
});
afterEach(() => {dispose?.();dispose=undefined;vi.restoreAllMocks();vi.useRealTimers();});
it('rotates document identity when a form disappears before its same-URL replacement',async()=>{
  dispose=startContentRuntime();const initial=messages.find((message)=>message.t==='cs/fields')!;
  if(initial.t!=='cs/fields') throw Error('fields expected');
  document.body.innerHTML='';await receive({t:'bg/scan'});
  const afterRemoval=messages.filter((message)=>message.t==='cs/ready').at(-1)!;
  expect(afterRemoval.documentId).not.toBe(initial.documentId);
  document.body.innerHTML='<label>Name<input name="name" /></label>';await receive({t:'bg/scan'});
  await receive({t:'bg/execute',documentId:initial.documentId,runId:'old',instructions:[{fieldId:initial.fields[0]!.fieldId,frameId:0,kind:'name.first',action:'setText',value:'Old draft',source:'user',confidence:1,requiresReview:false}]});
  const result=messages.filter((message)=>message.t==='cs/fillResults').at(-1)!;
  expect(result.t==='cs/fillResults'&&result.results[0]?.ok).toBe(false);expect(document.querySelector('input')!.value).toBe('');
});
it('aborts an in-flight execution when its controls disappear',async()=>{
  dispose=startContentRuntime();const initial=messages.find((message)=>message.t==='cs/fields')!;
  if(initial.t!=='cs/fields') throw Error('fields expected');
  const pending=receive({t:'bg/execute',documentId:initial.documentId,runId:'running',instructions:[{fieldId:initial.fields[0]!.fieldId,frameId:0,kind:'name.first',action:'setText',value:'Ada',source:'user',confidence:1,requiresReview:false}]});
  document.body.innerHTML='';await receive({t:'bg/scan'});await vi.advanceTimersByTimeAsync(200);await pending;
  const result=messages.filter((message)=>message.t==='cs/fillResults').at(-1)!;
  expect(result.t==='cs/fillResults'&&result.results[0]?.ok).toBe(false);
});
it('replaces duplicate initialization and releases timers on cleanup',()=>{
  const first=startContentRuntime();dispose=startContentRuntime();expect(disconnect).toHaveBeenCalledOnce();
  first();dispose();expect(vi.getTimerCount()).toBe(0);
});

it('attributes a generated version only to its successfully attached immutable file', async () => {
  document.body.innerHTML = '<form><label>Resume<input type="file" name="resume" /></label><button type="submit">Submit</button></form>';
  dispose = startContentRuntime();
  const initial = messages.find((message) => message.t === 'cs/fields');
  if (initial?.t !== 'cs/fields') throw Error('fields expected');
  const pending = receive({ t: 'bg/execute', documentId: initial.documentId, runId: 'attachment',
    instructions: [{ fieldId: initial.fields[0]!.fieldId, frameId: 0, kind: 'docs.resume', action: 'attachFile', value: { blobKey: 'generated', filename: 'resume.pdf' }, source: 'user', confidence: 1, requiresReview: false }],
    files: [{ blobKey: 'generated', name: 'resume.pdf', type: 'application/pdf', dataBase64: btoa('generated bytes') }],
    provenance: { profileId: 'profile-a', profileRevision: 2, resumeName: 'resume.pdf', resumeVersionId: 'version-a' } });
  await vi.advanceTimersByTimeAsync(300); await pending;
  document.querySelector('form')!.dispatchEvent(new Event('submit', { bubbles: true }));
  let attempt = messages.filter((message) => message.t === 'cs/submitAttempt').at(-1);
  expect(attempt?.t === 'cs/submitAttempt' && attempt.provenance).toMatchObject({ profileId: 'profile-a', resumeVersionId: 'version-a', resumeName: 'resume.pdf' });
  const transfer = new DataTransfer(); transfer.items.add(new File(['different bytes'], 'resume.pdf', { type: 'application/pdf' }));
  document.querySelector('input')!.files = transfer.files;
  document.querySelector('form')!.dispatchEvent(new Event('submit', { bubbles: true }));
  attempt = messages.filter((message) => message.t === 'cs/submitAttempt').at(-1);
  expect(attempt?.t === 'cs/submitAttempt' && attempt.provenance?.resumeName).toBe('resume.pdf');
  expect(attempt?.t === 'cs/submitAttempt' && attempt.provenance?.resumeVersionId).toBeUndefined();
});

it('does not attribute the default generated resume after an unrelated text-only fill', async () => {
  document.body.innerHTML = '<form><label>Name<input name="name" /></label><label>Resume<input type="file" name="resume" /></label></form>';
  const transfer = new DataTransfer(); transfer.items.add(new File(['manual bytes'], 'resume.pdf'));
  document.querySelector<HTMLInputElement>('input[type="file"]')!.files = transfer.files;
  dispose = startContentRuntime(); const initial = messages.find((message) => message.t === 'cs/fields');
  if (initial?.t !== 'cs/fields') throw Error('fields expected');
  const pending = receive({ t: 'bg/execute', documentId: initial.documentId, runId: 'text',
    instructions: [{ fieldId: initial.fields[0]!.fieldId, frameId: 0, kind: 'name.first', action: 'setText', value: 'Ada', source: 'user', confidence: 1, requiresReview: false }],
    provenance: { profileId: 'profile-a', resumeName: 'resume.pdf', resumeVersionId: 'default-version' } });
  await vi.advanceTimersByTimeAsync(300); await pending;
  document.querySelector('form')!.dispatchEvent(new Event('submit', { bubbles: true }));
  const attempt = messages.filter((message) => message.t === 'cs/submitAttempt').at(-1);
  expect(attempt?.t === 'cs/submitAttempt' && attempt.provenance?.resumeVersionId).toBeUndefined();
});
